### ISSUE TITLE
finos backend doesn't seem to be present (?)

### ISSUE THREAD

**Issue by jgbarah** [Bitergia/grimoirelab-perceval-finos#7]
I've just run (in the root of a clone of this repo):

```bash
$ python3 -m venv /tmp/gl-finos
$ source /tmp/gl-finos/bin/activate
$ pip install -e .
$ perceval finos --help
Traceback (most recent call last):
  File "/tmp/gl-finos/bin/perceval", line 158, in <module>
    main()
  File "/tmp/gl-finos/bin/perceval", line 96, in main
    raise RuntimeError("Unknown backend %s" % args.backend)
RuntimeError: Unknown backend finos
```

Any clue about the problem?

(Before running `pip install -e .` y installed the latest grimoirelab-toolkit, also from its repository, also using `pip install -e .` in it, because otherwise pip cannot satisfy dependencies for grimoirelab-perceval-finos)

**Comment by sduenas** [comment]
The name of the backend is `finosmeetings`.

**Comment by jgbarah** [comment]
Thanks!
